### PR TITLE
fix(internal/repo/config.go): fix typo

### PR DESCRIPTION
**Pull request by terasum**

### CODE REVIEW

**Comment by terasum** [comment]
The CI was failed, logs:

image

**Comment by 4ever9** [comment]
Thanks for your first pr.

**Comment by 4ever9** [comment]
LGTM

**Comment by 4ever9** [comment]
> The CI was failed, logs:
> 
> image

Rebase the latest master branch which had fixed the bug.

**Comment by jzhe886** [comment]
LGTM

**Pull request merged**
